version: '3'
services:
    devopsv5:
        image: davisliu/devopsv5:latest
        restart: always
        build: ./
        ports:
            - "80:8080"
        environment:
            - REDIS_HOST=redis
        links:
            - redis
    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
